import { MarketPriceRecord, MarketRecord, CommodityRecord, MarketArrivalRecord } from '../models/types.js'

export const seedMarkets: MarketRecord[] = [
  { id: 'MKT-HARDA', name: 'Harda APMC Mandi', district: 'Harda', state: 'Madhya Pradesh', distance_km_default: 18, is_active: true },
  { id: 'MKT-INDORE', name: 'Indore Central Mandi (Laxmibai Nagar)', district: 'Indore', state: 'Madhya Pradesh', distance_km_default: 145, is_active: true },
  { id: 'MKT-UJJAIN', name: 'Ujjain Agro Mandi', district: 'Ujjain', state: 'Madhya Pradesh', distance_km_default: 165, is_active: true },
  { id: 'MKT-BHOPAL', name: 'Bhopal Krishi Upaj Mandi (Karond)', district: 'Bhopal', state: 'Madhya Pradesh', distance_km_default: 155, is_active: true },
  { id: 'MKT-HOSHANG', name: 'Hoshangabad (Narmadapuram) Mandi', district: 'Narmadapuram', state: 'Madhya Pradesh', distance_km_default: 72, is_active: true },
  { id: 'MKT-VIDISHA', name: 'Vidisha APMC Mandi', district: 'Vidisha', state: 'Madhya Pradesh', distance_km_default: 180, is_active: true },
  { id: 'MKT-SEHORE', name: 'Sehore Krishi Mandi', district: 'Sehore', state: 'Madhya Pradesh', distance_km_default: 130, is_active: true },
  { id: 'MKT-KHANDWA', name: 'Khandwa APMC Mandi', district: 'Khandwa', state: 'Madhya Pradesh', distance_km_default: 95, is_active: true },
  { id: 'MKT-DEWAS', name: 'Dewas Agro Market Yard', district: 'Dewas', state: 'Madhya Pradesh', distance_km_default: 138, is_active: true },
  { id: 'MKT-KARNAL', name: 'Karnal Grain Market', district: 'Karnal', state: 'Haryana', distance_km_default: 820, is_active: true },
  { id: 'MKT-AMRITSAR', name: 'Amritsar Bhagtanwala Mandi', district: 'Amritsar', state: 'Punjab', distance_km_default: 980, is_active: true },
  { id: 'MKT-NASHIK', name: 'Nashik APMC Mandi', district: 'Nashik', state: 'Maharashtra', distance_km_default: 480, is_active: true },
]

export const seedCommodities: CommodityRecord[] = [
  { id: 'CMD-WHEAT', name: 'Wheat (Sharbati)', name_hi: 'गेहूं (शरबती)', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-SOYBEAN', name: 'Soybean', name_hi: 'सोयाबीन', category: 'Oilseeds', unit: '₹/qtl' },
  { id: 'CMD-RICE', name: 'Basmati Rice', name_hi: 'बासमती धान', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-CHANA', name: 'Chana (Gram)', name_hi: 'चना (देसी/डॉलर)', category: 'Pulses', unit: '₹/qtl' },
  { id: 'CMD-MUSTARD', name: 'Mustard', name_hi: 'सरसों', category: 'Oilseeds', unit: '₹/qtl' },
  { id: 'CMD-MAIZE', name: 'Maize', name_hi: 'मक्का', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-COTTON', name: 'Cotton (Kapas)', name_hi: 'कपास', category: 'Fibre', unit: '₹/qtl' },
]

export const seedPrices: MarketPriceRecord[] = [
  {
    id: 'PRC-001',
    state: 'Madhya Pradesh',
    district: 'Harda',
    market: 'Harda APMC Mandi',
    commodity: 'Wheat (Sharbati)',
    variety: 'C-306 Sharbati',
    grade: 'Grade A (FAQ)',
    arrival_date: '2026-05-18',
    min_price: 2590,
    max_price: 2850,
    modal_price: 2720,
    arrival_quantity: 480,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-002',
    state: 'Madhya Pradesh',
    district: 'Indore',
    market: 'Indore Central Mandi (Laxmibai Nagar)',
    commodity: 'Wheat (Sharbati)',
    variety: 'C-306 Sharbati Golden',
    grade: 'Grade A (Export)',
    arrival_date: '2026-05-18',
    min_price: 2680,
    max_price: 2950,
    modal_price: 2840,
    arrival_quantity: 1250,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-003',
    state: 'Madhya Pradesh',
    district: 'Harda',
    market: 'Harda APMC Mandi',
    commodity: 'Soybean',
    variety: 'JS-9560 Yellow',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4720,
    max_price: 5120,
    modal_price: 4940,
    arrival_quantity: 320,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-004',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    market: 'Ujjain Agro Mandi',
    commodity: 'Soybean',
    variety: 'JS-9305 Premium',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4850,
    max_price: 5240,
    modal_price: 5080,
    arrival_quantity: 890,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-005',
    state: 'Madhya Pradesh',
    district: 'Bhopal',
    market: 'Bhopal Krishi Upaj Mandi (Karond)',
    commodity: 'Basmati Rice',
    variety: 'Pusa 1121 Paddy',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4100,
    max_price: 4500,
    modal_price: 4320,
    arrival_quantity: 650,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-006',
    state: 'Madhya Pradesh',
    district: 'Harda',
    market: 'Harda APMC Mandi',
    commodity: 'Chana (Gram)',
    variety: 'Dollar Chana / Desi',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 5600,
    max_price: 6020,
    modal_price: 5850,
    arrival_quantity: 210,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-007',
    state: 'Madhya Pradesh',
    district: 'Narmadapuram',
    market: 'Hoshangabad (Narmadapuram) Mandi',
    commodity: 'Mustard',
    variety: 'Pusa Bold 540',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 5200,
    max_price: 5620,
    modal_price: 5460,
    arrival_quantity: 180,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-008',
    state: 'Madhya Pradesh',
    district: 'Vidisha',
    market: 'Vidisha APMC Mandi',
    commodity: 'Wheat (Sharbati)',
    variety: 'Vidisha Sharbati Special',
    grade: 'Grade A (Export)',
    arrival_date: '2026-05-18',
    min_price: 2650,
    max_price: 2920,
    modal_price: 2810,
    arrival_quantity: 740,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-009',
    state: 'Madhya Pradesh',
    district: 'Dewas',
    market: 'Dewas Agro Market Yard',
    commodity: 'Soybean',
    variety: 'Yellow Soybean',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4790,
    max_price: 5160,
    modal_price: 4980,
    arrival_quantity: 520,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-010',
    state: 'Haryana',
    district: 'Karnal',
    market: 'Karnal Grain Market',
    commodity: 'Basmati Rice',
    variety: 'Traditional Basmati 1509',
    grade: 'Grade A (Super)',
    arrival_date: '2026-05-18',
    min_price: 4400,
    max_price: 4850,
    modal_price: 4680,
    arrival_quantity: 1600,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
]

export const seedArrivals: MarketArrivalRecord[] = [
  { id: 'ARR-01', market: 'Harda APMC Mandi', district: 'Harda', state: 'Madhya Pradesh', commodity: 'Wheat (Sharbati)', arrival_date: '2026-05-18', quantity_tons: 48.0, source: 'DEMO DATA', is_demo: true, fetched_at: new Date().toISOString() },
  { id: 'ARR-02', market: 'Indore Central Mandi (Laxmibai Nagar)', district: 'Indore', state: 'Madhya Pradesh', commodity: 'Wheat (Sharbati)', arrival_date: '2026-05-18', quantity_tons: 125.0, source: 'DEMO DATA', is_demo: true, fetched_at: new Date().toISOString() },
  { id: 'ARR-03', market: 'Harda APMC Mandi', district: 'Harda', state: 'Madhya Pradesh', commodity: 'Soybean', arrival_date: '2026-05-18', quantity_tons: 32.0, source: 'DEMO DATA', is_demo: true, fetched_at: new Date().toISOString() },
  { id: 'ARR-04', market: 'Ujjain Agro Mandi', district: 'Ujjain', state: 'Madhya Pradesh', commodity: 'Soybean', arrival_date: '2026-05-18', quantity_tons: 89.0, source: 'DEMO DATA', is_demo: true, fetched_at: new Date().toISOString() },
  { id: 'ARR-05', market: 'Bhopal Krishi Upaj Mandi (Karond)', district: 'Bhopal', state: 'Madhya Pradesh', commodity: 'Basmati Rice', arrival_date: '2026-05-18', quantity_tons: 65.0, source: 'DEMO DATA', is_demo: true, fetched_at: new Date().toISOString() },
]

