import bcrypt from 'bcryptjs'
import {
  User,
  FarmerProfile,
  BuyerProfile,
  BuyerRequirement,
  CropLot,
  MarketPriceRecord,
  MarketRecord,
  CommodityRecord,
  MarketArrivalRecord,
  Offer,
  Transaction,
  TransportOption,
  StorageFacility,
  ActivityLog
} from '../models/types.js'

// Standard bcrypt hash for demo password 'password123'
export const DEFAULT_DEMO_PASSWORD_HASH = bcrypt.hashSync('password123', 10)

export const seedUsers: User[] = [
  {
    id: 'USR-FRM-01',
    email: 'ramesh@farmnexus.in',
    password_hash: DEFAULT_DEMO_PASSWORD_HASH,
    name: 'Ramesh Patel',
    phone: '+91 98261 44520',
    user_type: 'FARMER',
    location: 'Sirali, Harda',
    district: 'Harda',
    state: 'Madhya Pradesh',
    status: 'Active',
    kyc_verified: true,
    organization: 'Narmada Valley Kisan Producer Co.',
    created_at: '2024-10-14T09:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'USR-FRM-02',
    email: 'suresh@farmnexus.in',
    password_hash: DEFAULT_DEMO_PASSWORD_HASH,
    name: 'Suresh Choudhary',
    phone: '+91 94250 88120',
    user_type: 'FARMER',
    location: 'Barnagar, Ujjain',
    district: 'Ujjain',
    state: 'Madhya Pradesh',
    status: 'Active',
    kyc_verified: true,
    organization: 'Malwa Organic FPO Ltd.',
    created_at: '2024-11-02T10:30:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'USR-BUY-01',
    email: 'buyer@agrocorp.com',
    password_hash: DEFAULT_DEMO_PASSWORD_HASH,
    name: 'Sunil Aggarwal',
    phone: '+91 731 448900',
    user_type: 'BUYER',
    location: 'Indore Processing Terminal, AB Road',
    district: 'Indore',
    state: 'Madhya Pradesh',
    status: 'Active',
    kyc_verified: true,
    organization: 'AgroCorp Direct Procurement Ltd.',
    created_at: '2024-08-20T11:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'USR-BUY-02',
    email: 'procure@itc.in',
    password_hash: DEFAULT_DEMO_PASSWORD_HASH,
    name: 'Vijay Deshmukh',
    phone: '+91 7577 229100',
    user_type: 'BUYER',
    location: 'ITC Choupal Saagar Hub, Timarni',
    district: 'Harda',
    state: 'Madhya Pradesh',
    status: 'Active',
    kyc_verified: true,
    organization: 'ITC Choupal Saagar Rural Hub',
    created_at: '2024-09-05T14:20:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'USR-ADM-01',
    email: 'admin@farmnexus.in',
    password_hash: DEFAULT_DEMO_PASSWORD_HASH,
    name: 'State Operations Desk',
    phone: '+91 755 244890',
    user_type: 'ADMIN',
    location: 'State Agriculture Directorate, Bhopal',
    district: 'Bhopal',
    state: 'Madhya Pradesh',
    status: 'Active',
    kyc_verified: true,
    organization: 'FarmNexus State Directorate',
    created_at: '2024-01-01T08:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
]

export const seedFarmerProfiles: FarmerProfile[] = [
  {
    id: 'PRF-FRM-01',
    user_id: 'USR-FRM-01',
    fpo_name: 'Narmada Valley Kisan Producer Co.',
    fpo_role: 'Active Shareholder & Lead Producer',
    total_land_acres: 14.5,
    kisan_credit_card_verified: true,
    bank_account_masked: 'SBI •••• 8842',
    upi_id: 'ramesh.patel@sbi',
    village: 'Sirali, Harda',
    district: 'Harda',
    state: 'Madhya Pradesh',
    pincode: '461331',
    created_at: '2024-10-14T09:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'PRF-FRM-02',
    user_id: 'USR-FRM-02',
    fpo_name: 'Malwa Organic FPO Ltd.',
    fpo_role: 'Board Director',
    total_land_acres: 22.0,
    kisan_credit_card_verified: true,
    bank_account_masked: 'HDFC •••• 3120',
    upi_id: 'suresh.choudhary@hdfcbank',
    village: 'Barnagar',
    district: 'Ujjain',
    state: 'Madhya Pradesh',
    pincode: '456771',
    created_at: '2024-11-02T10:30:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
]

export const seedBuyerProfiles: BuyerProfile[] = [
  {
    id: 'PRF-BUY-01',
    user_id: 'USR-BUY-01',
    company_name: 'AgroCorp Direct Procurement Ltd.',
    gst_number: '23AAACA1234F1Z8',
    delivery_location: 'Indore Processing Terminal, AB Road',
    verified: true,
    reliability_score: 4.95,
    max_budget_inr: 5000000,
    created_at: '2024-08-20T11:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'PRF-BUY-02',
    user_id: 'USR-BUY-02',
    company_name: 'ITC Choupal Saagar Rural Hub',
    gst_number: '23AABCI5678R1Z2',
    delivery_location: 'Timarni Collection Center, Harda',
    verified: true,
    reliability_score: 4.98,
    max_budget_inr: 10000000,
    created_at: '2024-09-05T14:20:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
]

export const seedBuyerRequirements: BuyerRequirement[] = [
  {
    id: 'REQ-01',
    buyer_id: 'USR-BUY-01',
    required_crop: 'Wheat (Sharbati)',
    required_quantity_qtl: 100,
    preferred_grade: 'Grade A',
    preferred_location: 'Madhya Pradesh',
    max_price: 2900,
    created_at: '2026-05-01T10:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
]

export const seedLots: CropLot[] = [
  {
    id: 'LOT-AGN-081',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    crop: 'Wheat (Sharbati)',
    crop_hi: 'गेहूं (शरबती)',
    category: 'Grains & Cereals',
    variety: 'C-306 Sharbati Premium',
    quantity_qtl: 140,
    unit: 'Quintal',
    grade: 'Grade A (Export)',
    expected_price: 2750,
    min_acceptable_price: 2650,
    market_reference_price: 2840,
    status: 'Active',
    location: 'Sirali, Harda, MP',
    district: 'Harda',
    state: 'Madhya Pradesh',
    pickup_location: 'Sirali Farm Godown #2, Harda',
    is_demo: true,
    quality: {
      lot_id: 'LOT-AGN-081',
      grade: 'Grade A (Export)',
      visual_quality: 'Excellent',
      damage_level: 'None',
      grain_size: 'Uniform Bold',
      moisture_percent: 10.4,
      foreign_matter_percent: 0.8,
      notes: 'Harvested in optimal dry conditions. Zero pest damage, uniform golden luster.',
      images: ['/wheat_sample.jpg'],
    },
    active_offers_count: 2,
    highest_offer: 2780,
    created_at: '2026-05-14T08:00:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'LOT-AGN-092',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    crop: 'Soybean',
    crop_hi: 'सोयाबीन',
    category: 'Oilseeds',
    variety: 'JS-335 Certified Seed',
    quantity_qtl: 95,
    unit: 'Quintal',
    grade: 'Grade A',
    expected_price: 4850,
    min_acceptable_price: 4700,
    market_reference_price: 4940,
    status: 'Active',
    location: 'Sirali, Harda, MP',
    district: 'Harda',
    state: 'Madhya Pradesh',
    pickup_location: 'Sirali Warehouse Bay #1',
    is_demo: true,
    quality: {
      lot_id: 'LOT-AGN-092',
      grade: 'Grade A',
      visual_quality: 'Good',
      damage_level: 'None',
      grain_size: 'Uniform Bold',
      moisture_percent: 11.2,
      foreign_matter_percent: 1.1,
      notes: 'High oil yield content verified by Narmada FPO assay lab.',
    },
    active_offers_count: 1,
    highest_offer: 4920,
    created_at: '2026-05-12T09:30:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
  {
    id: 'LOT-AGN-074',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    crop: 'Basmati Rice',
    crop_hi: 'बासमती चावल',
    category: 'Grains & Cereals',
    variety: 'Pusa 1121 Export Grade',
    quantity_qtl: 50,
    unit: 'Quintal',
    grade: 'Grade A (Export)',
    expected_price: 4200,
    min_acceptable_price: 4100,
    market_reference_price: 4350,
    status: 'Active',
    location: 'Sirali, Harda, MP',
    district: 'Harda',
    state: 'Madhya Pradesh',
    pickup_location: 'Sirali Farm Gate',
    is_demo: true,
    quality: {
      lot_id: 'LOT-AGN-074',
      grade: 'Grade A (Export)',
      visual_quality: 'Excellent',
      damage_level: 'None',
      grain_size: 'Uniform Bold',
      moisture_percent: 12.0,
      foreign_matter_percent: 0.5,
      notes: 'Long grain slender, 8.4mm average cooked length potential.',
    },
    active_offers_count: 1,
    highest_offer: 4300,
    created_at: '2026-05-10T11:15:00.000Z',
    updated_at: '2026-05-18T10:00:00.000Z',
  },
]

export const seedMarkets: MarketRecord[] = [
  { id: 'MKT-HARDA', name: 'Harda APMC Mandi', district: 'Harda', state: 'Madhya Pradesh', distance_km_default: 18, is_active: true },
  { id: 'MKT-INDORE', name: 'Indore Central Mandi (Laxmibai Nagar)', district: 'Indore', state: 'Madhya Pradesh', distance_km_default: 145, is_active: true },
  { id: 'MKT-UJJAIN', name: 'Ujjain Agro Mandi', district: 'Ujjain', state: 'Madhya Pradesh', distance_km_default: 165, is_active: true },
  { id: 'MKT-BHOPAL', name: 'Bhopal Krishi Upaj Mandi (Karond)', district: 'Bhopal', state: 'Madhya Pradesh', distance_km_default: 155, is_active: true },
  { id: 'MKT-HOSHANG', name: 'Hoshangabad (Narmadapuram) Mandi', district: 'Narmadapuram', state: 'Madhya Pradesh', distance_km_default: 72, is_active: true },
  { id: 'MKT-VIDISHA', name: 'Vidisha APMC Mandi', district: 'Vidisha', state: 'Madhya Pradesh', distance_km_default: 180, is_active: true },
]

export const seedCommodities: CommodityRecord[] = [
  { id: 'CMD-WHEAT', name: 'Wheat (Sharbati)', name_hi: 'गेहूं (शरबती)', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-SOYBEAN', name: 'Soybean', name_hi: 'सोयाबीन', category: 'Oilseeds', unit: '₹/qtl' },
  { id: 'CMD-RICE', name: 'Basmati Rice', name_hi: 'बासमती धान', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-CHANA', name: 'Chana (Gram)', name_hi: 'चना (देसी/डॉलर)', category: 'Pulses', unit: '₹/qtl' },
  { id: 'CMD-MUSTARD', name: 'Mustard', name_hi: 'सरसों', category: 'Oilseeds', unit: '₹/qtl' },
  { id: 'CMD-MAIZE', name: 'Maize', name_hi: 'मक्का', category: 'Cereals', unit: '₹/qtl' },
  { id: 'CMD-COTTON', name: 'Cotton (Kapas)', name_hi: 'कपास', category: 'Fibre', unit: '₹/qtl' },
]

export const seedArrivals: MarketArrivalRecord[] = [
  { id: 'ARV-001', market: 'Indore Central Mandi (Laxmibai Nagar)', district: 'Indore', state: 'Madhya Pradesh', commodity: 'Wheat (Sharbati)', arrival_date: '2026-05-18', quantity_tons: 125, source: 'APMC Gate Weighbridge', is_demo: true, fetched_at: new Date().toISOString() },
  { id: 'ARV-002', market: 'Harda APMC Mandi', district: 'Harda', state: 'Madhya Pradesh', commodity: 'Soybean', arrival_date: '2026-05-18', quantity_tons: 48, source: 'APMC Gate Weighbridge', is_demo: true, fetched_at: new Date().toISOString() },
]

export const seedPrices: MarketPriceRecord[] = [
  {
    id: 'PRC-001',
    state: 'Madhya Pradesh',
    district: 'Harda',
    market: 'Harda APMC Mandi',
    commodity: 'Wheat (Sharbati)',
    variety: 'C-306 Sharbati',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 2590,
    max_price: 2850,
    modal_price: 2720,
    price_change: 1.8,
    trend: 'up',
    arrival_quantity: 480,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-002',
    state: 'Madhya Pradesh',
    district: 'Indore',
    market: 'Indore Central Mandi (Laxmibai Nagar)',
    commodity: 'Wheat (Sharbati)',
    variety: 'C-306 Sharbati Golden',
    grade: 'Grade A (Export)',
    arrival_date: '2026-05-18',
    min_price: 2680,
    max_price: 2950,
    modal_price: 2840,
    price_change: 3.4,
    trend: 'up',
    arrival_quantity: 1250,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-003',
    state: 'Madhya Pradesh',
    district: 'Ujjain',
    market: 'Ujjain Agro Mandi',
    commodity: 'Wheat (Sharbati)',
    variety: 'Lokwan / Sharbati',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 2610,
    max_price: 2890,
    modal_price: 2790,
    price_change: 2.1,
    trend: 'up',
    arrival_quantity: 940,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-004',
    state: 'Madhya Pradesh',
    district: 'Harda',
    market: 'Harda APMC Mandi',
    commodity: 'Soybean',
    variety: 'JS-9560 Yellow',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4720,
    max_price: 5120,
    modal_price: 4940,
    price_change: 2.8,
    trend: 'up',
    arrival_quantity: 320,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-005',
    state: 'Madhya Pradesh',
    district: 'Indore',
    market: 'Indore Central Mandi (Laxmibai Nagar)',
    commodity: 'Soybean',
    variety: 'JS-335 Yellow',
    grade: 'Grade A',
    arrival_date: '2026-05-18',
    min_price: 4800,
    max_price: 5200,
    modal_price: 5040,
    price_change: 1.5,
    trend: 'up',
    arrival_quantity: 1100,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
  {
    id: 'PRC-006',
    state: 'Madhya Pradesh',
    district: 'Narmadapuram',
    market: 'Hoshangabad Mandi Yard',
    commodity: 'Basmati Rice',
    variety: 'Pusa 1121',
    grade: 'Grade A (Export)',
    arrival_date: '2026-05-18',
    min_price: 4150,
    max_price: 4450,
    modal_price: 4320,
    price_change: 0.9,
    trend: 'steady',
    arrival_quantity: 650,
    source: 'DEMO DATA (Baseline Mandi Feed)',
    is_demo: true,
    fetched_at: new Date().toISOString(),
  },
]

export const seedOffers: Offer[] = [
  {
    id: 'OFF-8950',
    lot_id: 'LOT-AGN-081',
    lot_title: 'Wheat (Sharbati) • 60 qtl',
    buyer_id: 'USR-BUY-01',
    buyer_name: 'Sunil Aggarwal',
    buyer_company: 'AgroCorp Direct Procurement Ltd.',
    buyer_reliability: 4.95,
    buyer_verified: true,
    offered_price: 2780,
    lot_expected_price: 2750,
    quantity_qtl: 60,
    total_amount: 166800,
    payment_terms: 'e-NWR Escrow auto-release on gate receipt',
    pickup_location: 'Indore APMC Processing Bay #4',
    status: 'Accepted',
    created_at: '2026-05-14T09:30:00.000Z',
    updated_at: '2026-05-14T09:32:00.000Z',
  },
  {
    id: 'OFF-8951',
    lot_id: 'LOT-AGN-092',
    lot_title: 'Soybean (Yellow) • 95 qtl',
    buyer_id: 'USR-BUY-02',
    buyer_name: 'Vijay Deshmukh',
    buyer_company: 'ITC Choupal Saagar Rural Hub',
    buyer_reliability: 4.98,
    buyer_verified: true,
    offered_price: 4920,
    lot_expected_price: 4850,
    quantity_qtl: 95,
    total_amount: 467400,
    payment_terms: 'Direct UPI Bank release on gate weighing',
    pickup_location: 'Farm-gate pickup Sirali',
    status: 'Accepted',
    created_at: '2026-05-12T11:00:00.000Z',
    updated_at: '2026-05-12T11:05:00.000Z',
  },
  {
    id: 'OFF-8952',
    lot_id: 'LOT-AGN-074',
    lot_title: 'Basmati Rice (Pusa 1121) • 50 qtl',
    buyer_id: 'USR-BUY-01',
    buyer_name: 'Sunil Aggarwal',
    buyer_company: 'AgroCorp Direct Procurement Ltd.',
    buyer_reliability: 4.95,
    buyer_verified: true,
    offered_price: 4300,
    lot_expected_price: 4200,
    quantity_qtl: 50,
    total_amount: 215000,
    payment_terms: 'e-NWR Escrow Vault',
    pickup_location: 'Hoshangabad APMC Export Terminal',
    status: 'Pending',
    created_at: '2026-05-14T08:45:00.000Z',
    updated_at: '2026-05-14T08:45:00.000Z',
  },
]

export const seedTransactions: Transaction[] = [
  {
    id: 'TXN-2026-9041',
    lot_id: 'LOT-AGN-081',
    offer_id: 'OFF-8950',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    farmer_location: 'Sirali Farm Godown #2, Harda, MP',
    farmer_phone: '+91 98261 44520',
    buyer_id: 'USR-BUY-01',
    buyer_name: 'Sunil Aggarwal',
    buyer_organization: 'AgroCorp Direct Procurement Ltd.',
    buyer_location: 'Indore Processing Terminal, MP',
    crop: 'Wheat (Sharbati)',
    crop_hi: 'गेहूं (शरबती)',
    variety: 'C-306 Sharbati Premium',
    quantity_qtl: 60,
    unit: 'Quintal',
    agreed_price_per_qtl: 2780,
    produce_value: 166800,
    transport_cost: 4930,
    mandi_cess: 2502,
    final_amount: 171730,
    mandi_or_delivery_location: 'Indore APMC Processing Bay #4',
    payment_status: 'Payment Successful',
    transaction_status: 'In Transit',
    timeline: [
      { stage: 'offer_accepted', label: 'Offer Accepted by Farmer', timestamp: 'May 14, 09:30 AM', completed: true, description: 'Agreed price ₹2,780/qtl for 60 quintals.' },
      { stage: 'transaction_created', label: 'Transaction Contract Binding', timestamp: 'May 14, 09:32 AM', completed: true, description: 'Electronic trade contract generated.' },
      { stage: 'escrow_funded', label: 'Buyer Escrow Funded', timestamp: 'May 14, 10:15 AM', completed: true, description: '[Demo Settlement Reference] ₹1,71,730 verified in virtual settlement ledger.' },
      { stage: 'in_transit', label: 'Produce Dispatched & In Transit', timestamp: 'May 14, 02:00 PM', completed: true, description: 'Carrier Vehicle MP-09-GH-4120 dispatched from Sirali.' },
      { stage: 'delivered', label: 'Delivery & Gate Assay Check', timestamp: 'Pending', completed: false, description: 'Produce arrival at Indore processing dock.' },
      { stage: 'completed', label: 'Escrow Settlement to Farmer SBI', timestamp: 'Pending', completed: false, description: 'Auto-release upon digital delivery receipt.' },
    ],
    payment_details: {
      method: 'e-NWR Escrow',
      transaction_ref: 'DEMO-SETTLE-REF-8492019',
      payer_vpa: 'agrocorp.procure@upi',
      paid_at: 'May 14, 2026, 10:15 AM',
      escrow_ref: 'DEMO-ESC-TRX-948201',
    },
    created_at: '2026-05-14T09:30:00.000Z',
    updated_at: '2026-05-14T14:00:00.000Z',
  },
  {
    id: 'TXN-2026-8812',
    lot_id: 'LOT-AGN-092',
    offer_id: 'OFF-8951',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    farmer_location: 'Sirali Farm Godown #2, Harda, MP',
    farmer_phone: '+91 98261 44520',
    buyer_id: 'USR-BUY-02',
    buyer_name: 'Vijay Deshmukh',
    buyer_organization: 'ITC Choupal Saagar Rural Hub',
    buyer_location: 'Timarni Collection Center, Harda',
    crop: 'Soybean (Yellow)',
    crop_hi: 'सोयाबीन',
    variety: 'JS-335 Certified Seed',
    quantity_qtl: 95,
    unit: 'Quintal',
    agreed_price_per_qtl: 4920,
    produce_value: 467400,
    transport_cost: 0,
    mandi_cess: 7011,
    final_amount: 467400,
    mandi_or_delivery_location: 'Farm-gate pickup Sirali',
    payment_status: 'Payment Successful',
    transaction_status: 'Completed',
    timeline: [
      { stage: 'offer_accepted', label: 'Offer Accepted by Farmer', timestamp: 'May 12, 11:00 AM', completed: true, description: 'Agreed price ₹4,920/qtl for 95 quintals.' },
      { stage: 'transaction_created', label: 'Transaction Contract Binding', timestamp: 'May 12, 11:05 AM', completed: true, description: 'Electronic trade contract generated.' },
      { stage: 'escrow_funded', label: 'Buyer Escrow Funded', timestamp: 'May 12, 11:30 AM', completed: true, description: '₹4,67,400 secured in escrow.' },
      { stage: 'in_transit', label: 'Farm-gate Weighing & Loading', timestamp: 'May 12, 03:00 PM', completed: true, description: 'Loaded into ITC collection truck.' },
      { stage: 'delivered', label: 'Delivered at Collection Center', timestamp: 'May 12, 05:30 PM', completed: true, description: 'Moisture 10.1% verified.' },
      { stage: 'completed', label: 'Funds Disbursed to Farmer SBI', timestamp: 'May 12, 06:15 PM', completed: true, description: 'Direct transfer to SBI •••• 8842.' },
    ],
    payment_details: {
      method: 'UPI',
      transaction_ref: 'UPI-SBI-9948201',
      payer_vpa: 'itc.choupal@hdfcbank',
      paid_at: 'May 12, 2026, 06:15 PM',
      escrow_ref: 'ESC-TRX-224810',
    },
    created_at: '2026-05-12T11:00:00.000Z',
    updated_at: '2026-05-12T18:15:00.000Z',
  },
  {
    id: 'TXN-2026-9901',
    lot_id: 'LOT-AGN-074',
    offer_id: 'OFF-8952',
    farmer_id: 'USR-FRM-01',
    farmer_name: 'Ramesh Patel',
    farmer_location: 'Sirali Farm Godown #2, Harda, MP',
    farmer_phone: '+91 98261 44520',
    buyer_id: 'USR-BUY-01',
    buyer_name: 'Sunil Aggarwal',
    buyer_organization: 'AgroCorp Direct Procurement Ltd.',
    buyer_location: 'Indore Processing Terminal, MP',
    crop: 'Basmati Rice (Pusa 1121)',
    crop_hi: 'बासमती चावल',
    variety: 'Pusa 1121 Export Grade',
    quantity_qtl: 50,
    unit: 'Quintal',
    agreed_price_per_qtl: 5560,
    produce_value: 278000,
    transport_cost: 0,
    mandi_cess: 0,
    final_amount: 278000,
    mandi_or_delivery_location: 'Indore Processing Terminal, MP',
    payment_status: 'Payment Pending',
    transaction_status: 'Payment Pending',
    timeline: [
      { stage: 'offer_accepted', label: 'Offer Accepted by Farmer', timestamp: 'May 18, 10:00 AM', completed: true, description: 'Agreed price ₹5,560/qtl for 50 quintals.' },
      { stage: 'transaction_created', label: 'Transaction Contract Binding', timestamp: 'May 18, 10:05 AM', completed: true, description: 'Electronic trade contract generated.' },
      { stage: 'escrow_funded', label: 'Buyer Escrow Funded', timestamp: 'Pending', completed: false, description: 'Awaiting Razorpay escrow deposit.' },
      { stage: 'in_transit', label: 'Produce Dispatched & In Transit', timestamp: 'Pending', completed: false, description: 'Carrier dispatch.' },
      { stage: 'delivered', label: 'Delivery & Gate Assay Check', timestamp: 'Pending', completed: false, description: 'Produce arrival at Indore dock.' },
      { stage: 'completed', label: 'Escrow Settlement to Farmer SBI', timestamp: 'Pending', completed: false, description: 'Auto-release upon delivery receipt.' },
    ],
    created_at: '2026-05-18T10:00:00.000Z',
    updated_at: '2026-05-18T10:05:00.000Z',
  },
]

export const seedTransportOptions: TransportOption[] = [
  { id: 'TRP-01', vehicle_type: 'Small Commercial (Tata Ace / 1.5 MT)', capacity_qtl: 15, base_fare: 800, per_km_rate: 18, avg_speed_kmh: 40, is_active: true },
  { id: 'TRP-02', vehicle_type: 'Tractor-Trolley (Standard / 4.0 MT)', capacity_qtl: 40, base_fare: 1200, per_km_rate: 24, avg_speed_kmh: 30, is_active: true },
  { id: 'TRP-03', vehicle_type: 'Medium Truck (Eicher 6-Wheeler / 7.5 MT)', capacity_qtl: 75, base_fare: 2200, per_km_rate: 34, avg_speed_kmh: 45, is_active: true },
  { id: 'TRP-04', vehicle_type: 'Heavy Multi-Axle Truck (16.0 MT)', capacity_qtl: 160, base_fare: 4000, per_km_rate: 52, avg_speed_kmh: 50, is_active: true },
]

export const seedStorageFacilities: StorageFacility[] = [
  {
    id: 'STR-MP-01',
    name: 'MP Warehousing & Logistics Corp (MPWLC) Harda Hub',
    type: 'State Govt. Warehouse (WDRA Approved)',
    location: 'Indore-Betul Road, Sirali Turn, Harda',
    district: 'Harda',
    state: 'Madhya Pradesh',
    total_capacity_mt: 5000,
    available_capacity_mt: 1450,
    daily_rate_per_bag: 0.28,
    is_wdra_registered: true,
    cold_storage_enabled: false,
    pest_controlled: true,
    contact_phone: '+91 7577 222140',
    latitude: 22.3364,
    longitude: 77.0984,
  },
  {
    id: 'STR-MP-02',
    name: 'Central Warehousing Corporation (CWC) Timarni Silos',
    type: 'Central Govt. Scientific Silo Complex',
    location: 'Timarni Railway Siding, Harda District',
    district: 'Harda',
    state: 'Madhya Pradesh',
    total_capacity_mt: 12000,
    available_capacity_mt: 3800,
    daily_rate_per_bag: 0.32,
    is_wdra_registered: true,
    cold_storage_enabled: false,
    pest_controlled: true,
    contact_phone: '+91 7577 234890',
    latitude: 22.3712,
    longitude: 77.2341,
  },
]

export const seedActivityLogs: ActivityLog[] = [
  {
    id: 'LOG-101',
    action: 'Market Price Updated',
    admin_id: 'USR-ADM-01',
    admin_user: 'State Operations Desk',
    target_type: 'MarketPrice',
    target_id: 'Indore APMC - Wheat (Sharbati)',
    details: 'Modal price revised to ₹2,840/qtl based on AGMARKNET mandi arrival feed.',
    timestamp: 'Today, 10:30 AM',
    created_at: new Date().toISOString(),
  },
  {
    id: 'LOG-102',
    action: 'User KYC Verified',
    admin_id: 'USR-ADM-01',
    admin_user: 'State Operations Desk',
    target_type: 'User',
    target_id: 'USR-BUY-01 (AgroCorp Direct)',
    details: 'GSTIN 23AAACA1234F1Z8 and bank mandate verified with ICICI Bank.',
    timestamp: 'Yesterday, 04:15 PM',
    created_at: new Date().toISOString(),
  },
]
